ivpn/ivpn.net

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
> Enables ISP and Server Load columns on the server status page

- src/content/blog/privacy-issue-real-vpns-alone-cant-solve-it.md
Fix URL for blog post:  
https://www.ivpn.net/blog/privacy-issue-real-vpns-alone-cant-solve-it/
> Fix blog post URL

- src/content/blog/privacy-issue-real-vpns-alone-cant-solve-it.md
- src/content/pages/knowledgebase/mp/how-to-use-ivpn-on-kodi-media-player.md
- src/themes/ivpn-v3/layouts/blog/single.html
Update internal URLs to include trailing `/`.
> Update internal URLs

- nginx.conf
Add 301 redirects:  
- /what-is-a-multihop-vpn -> /
- /data-retention-laws/united-kingdom -> /blog/collection-of-user-data-by-isps-and-telecom-providers-and-sharing-with-third-parties/
- /data-retention-laws/united-states -> /blog/collection-of-user-data-by-isps-and-telecom-providers-and-sharing-with-third-parties/
- /comparison-of-internet-privacy-laws -> /blog/collection-of-user-data-by-isps-and-telecom-providers-and-sharing-with-third-parties/
- /internet-privacy-laws-in-the-united-kingdom -> /blog/collection-of-user-data-by-isps-and-telecom-providers-and-sharing-with-third-parties/
- /internet-privacy-laws-in-the-united-states -> /blog/collection-of-user-data-by-isps-and-telecom-providers-and-sharing-with-third-parties/
> Add 301 redirects

- src/themes/ivpn-v3/assets/scss/components/heading.scss
Team page: https://www.ivpn.net/team
Paragraph and CTA not aligned with the header
> Text related issues

- src/themes/ivpn-v3/assets/js/views/Prices.vue
Update Money back guarantee text
> Update Money back guarantee text in Prices.vue

- src/themes/ivpn-v3/data/.gitignore
- src/themes/ivpn-v3/data/manifest.json
This pull requests removes built-time intermediate file: manifest.json
> Removes manifest.json file from repository

- src/content/pages/knowledgebase/billing/paid-with-paypal-using-echeck-but-ivpn-account-is-still-in-pendingorsuspended-state-why.md
- [ X] Documentation content changes
- [X ] No
> Minor KB formatting edit

- src/content/pages/knowledgebase/billing/does-ivpn-offer-a-free-trial.md
> Edit kb article

- src/content/pages/setup/android-ipsec-with-ikev2.md
- src/content/pages/setup/android-openvpn-for-android.md
- src/content/pages/setup/ipad-ipsec-ikev2.md
- src/content/pages/setup/ipad-openvpn-connect.md
- src/content/pages/setup/iphone-ipsec-ikev2.md
- src/content/pages/setup/iphone-openvpn-connect.md
- src/content/pages/setup/linux-netman.md
- src/content/pages/setup/linux-terminal.md
- src/content/pages/setup/macos-ipsec-with-ikev2.md
- src/content/pages/setup/macos-openvpn-tunnelblick.md
- src/content/pages/setup/nas/qnap.md
- src/content/pages/setup/nas/synology-6.md
- src/content/pages/setup/router/asuswrt.md
- src/content/pages/setup/router/ddwrt-auto.md
- src/content/pages/setup/router/ddwrt-manual.md
- src/content/pages/setup/router/pfsense.md
- src/content/pages/setup/router/tomato-manual.md
- src/content/pages/setup/windows-10-ipsec-with-ikev2.md
- src/content/pages/setup/windows-10-openvpn-community.md
- src/content/pages/setup/windows-8-openvpn-community.md
> Setup guides update

- src/content/pages/knowledgebase/general/do-you-offer-openvpn-config-files-for-tcp-connections.md
> Fix link for TCP-based OpenVPN files, commas

- src/content/pages/apps-android.md
> Android client version 2.1.0

- src/themes/ivpn-v3/assets/js/api/api.js
- src/themes/ivpn-v3/assets/js/assets/icons/giftcard.svg
- src/themes/ivpn-v3/assets/js/components/PriceBox.vue
- src/themes/ivpn-v3/assets/js/components/SelectPaymentMethod.vue
- src/themes/ivpn-v3/assets/js/router/index.js
- src/themes/ivpn-v3/assets/js/store/module_payments.js
- src/themes/ivpn-v3/assets/js/store/module_product.js
- src/themes/ivpn-v3/assets/js/styles/icons.scss
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/CC.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/GiftCard.vue
- src/themes/ivpn-v3/assets/js/views/Account/Payment.vue
VPN service can now be extended using Gift Cards which are distributed with variety of methods outside of our website.
> Support extending service using Gift Cards

- src/content/pages/home.md
Meta information (title, description) is updated for the Home page.
> Update meta info in home.md

- nginx.conf
Special characters in `.txt` files are not displayed correctly.
Encoding is now explicitly set to UTF-8, for text files included.
> Charset for text files

- src/themes/ivpn-v3/assets/scss/elements/img.scss
> Update figure captions styles

- src/config/_default/config.toml
- src/config/production/config.toml
- src/config/staging/config.toml
- src/content/blog/2014-01-14-dont-expect-googles-conscious-home-to-keep-things-private.md
- src/themes/ivpn-v3/layouts/partials/footer.html
Renamed configuration parameters and script name from piwik to matomo
> Renames Piwik to Matomo in configuration files

- src/content/pages/knowledgebase/linux/linux-client-faq.md
The article offers a link to the outdated AUR community "ivpn-git" package.
The article offers links to the two new official AUR packages.
This article may be moot or has the potential to be removed based on the upcoming changes to the Linux App download page redesign.
> Update AUR links in install step

- src/themes/ivpn-v3/assets/js/components/SelectPaymentMethod.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/GiftCard.vue
This change puts "Gift Payments" option in the submenu, so it doesn't distract users from other valid options, 
since we're not yet distributing Gift Cards.
> Moves "IVPN Gift Card" payment option under "additional payments" menu

- src/content/blog/ivpn-apps-on-all-platforms-to-undergo-security-audit.md
New blog post:  
"IVPN apps on all platforms to undergo security audit"
> New blog post

- src/content/pages/knowledgebase/android/unable-to-click-andsharp039okandsharp039-on-the-connection-request-prompt-why.md
- src/content/pages/knowledgebase/android/what permissions does your app require and why?.md
> Adding new KB article

- nginx.conf
- src/themes/ivpn-v3/assets/scss/components/heading.scss
- src/themes/ivpn-v3/assets/scss/fonts/roboto-mono/font.scss
- src/themes/ivpn-v3/layouts/_default/baseof.html
- src/themes/ivpn-v3/layouts/partials/blocks/features_image_three_column.html
- src/themes/ivpn-v3/layouts/partials/blocks/heading_text_two_cta_two_column.html
- src/themes/ivpn-v3/layouts/partials/footer.html
- src/themes/ivpn-v3/layouts/partials/header.html
Performance optimisations for faster Home page load.
> Home page performance optimisation

- src/themes/ivpn-v3/assets/scss/components/image.scss
- src/themes/ivpn-v3/layouts/partials/blocks/image_full_width.html
Performance optimisations for faster Team page load.
> Team page performance optimisation

- src/themes/ivpn-v3/assets/js/api/api.js
- src/themes/ivpn-v3/assets/js/store/module_braintree.js
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/CC.vue
Ocassionally, backend need to prove that user is not a bot, so it requests captcha to be solved.
This commit adds support for the frontend to show captcha to the user when requested by the backend.
> Adds support for Captcha response when making a payment.

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/CC.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/PayPal.vue
Adds support for "Captcha Required" error from backend to PayPal payment form
> Adds support for "Captcha Required" error from backend to PayPal payment form

- src/content/pages/knowledgebase/linux/building-the-ivpn-cli-client-for-linux-on-a-raspberry-pi.md
> Fix local git path

- src/content/pages/apps-linux.md
> New Linux binaries update info

- src/config/_default/config.toml
RSS feed for blog section will be published at:  
[https://www.ivpn.net/blog/index.xml](https://www.ivpn.net/blog/index.xml)  
Resolves #41
> Publish RSS feed for blog

- src/themes/ivpn-v3/assets/js/components/popups/TotpEnable.vue
On light theme, the backup codes have a background from dark theme.
Correct styles are now applied to both light and dark themes.
> UI issue on 2-Factor Authentication popup

- src/themes/ivpn-v3/yarn.lock
> Upgrade yarn dependencies to the latest version

- src/content/pages/knowledgebase/general/what-payment-methods-do-you-accept.md
> Update payment method list to include Monero

- src/content/pages/manifesto.md
"Today’s internet looks very different – having been captured by the market forces of the surveillance economy, whose fuel is every detail our personal lives."
https://cloud.tchncs.de/s/3ePaMkFRY6wTLLx/preview
> A word missing in a sentence on manifesto.md

- src/content/pages/ethics.md
"Every decision matters: how and what we communicate to new customers, what we information we collect and what tools we use to improve our service." Should be `what information we`
> Accidental duplication of a word on ethics.md

- src/content/pages/privacy-policy.md
Multiple typos, incomplete/broken sentences and suggestions.
Add, drop, improvise as you prefer. I just wanted to point out.
I made changes to some and some needs supervision.
(If you happen to plan on going through whole privacy policy, you could use "find in page", save time)
\
\
\
1.(edited) Typo: principals ➤ principles
\
\
2.(edited) Typo: its (2x) ➤ it's
\
\
3.(no change) Suggestion: While implication of "human-readable" is understandable, still (IMO) this wording might be better ➤ We’ve tried our best to make this policy `simple and easy to understand` so you can get the facts you need quickly.
\
\
4.(no change) Suggestion: "As a privacy service we believe it’s.." ➤ As a privacy `focused` service we believe it’s..
\
\
5.(edited) Typo/ Suggestion?: "Some payment information may be …
> Multiple typos, fixes needed on privacy-policy.md

- src/content/pages/privacy-policy.md
Adding Device Permissions section to Privacy Policy
> Privacy Policy update

- src/content/pages/apps-android.md
- src/content/pages/apps-ios.md
- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
- src/content/pages/setup/linux-terminal.md
For some reason, I can never find the TCP option on the site. This should make it easier for the user to chose.
> TCP Option

- src/content/pages/knowledgebase/routers/how-to-enable-a-andsharp039kill-switchandsharp039-in-my-dd-wrtortomato-router.md
> Update router killswitch KB article

- src/themes/ivpn-v3/assets/js/views/Prices.vue
Adds "Monero" payment method to a pricing page description
> Adds "Monero" payment method to a pricing page description

- src/content/pages/apps-android.md
> Release new Android v2.2.0

- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> App updates/2.12.17

- nginx.conf
Updated redirect: `/signup` -> `/pricing/`
> Update pricing page redirect

- src/content/pages/privacy-guides/advanced-privacy-and-anonymity-part-3.md
Fixed URL (added trailing `/`) in /privacy-guides/advanced-privacy-and-anonymity-part-3.
> Fix URL in /privacy-guides/advanced-privacy-and-anonymity-part-3

- src/themes/ivpn-v3/assets/js/app.js
- src/themes/ivpn-v3/assets/js/components/PriceBox.vue
- src/themes/ivpn-v3/assets/js/components/SelectBillingCycle.vue
Instead of displaying discount in percentages (for example -20%), we display full price without discount striked-though.
> Changes the way discounts are displayed

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/BitCoin.vue
Temporarily disabled Bitcoin payment.
> Disables BitCoin payments

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/BitCoin.vue
> Revert "Disables Bitcoin payments"

- src/themes/ivpn-v3/assets/js/components/AccountInfo.vue
Increased size of the QR code in Account details view.
Resolves #85
> Make the QR code on the account section bigger

- src/themes/ivpn-v3/assets/scss/elements/headings.scss
Reduced font size for `h1` elements, for small screens.
Resolves: #84
> Cutoff in the Home screen on small devices

- src/themes/ivpn-v3/assets/js/components/AccountInfo.vue
> Fixes the location of "Scan from our mobile apps" note under the QR Code

- src/content/pages/knowledgebase/general/custom-dns.md
> Update Custom DNS article for new app design

- src/content/pages/knowledgebase/general/do-you-offer-a-kill-switch-or-vpn-firewall.md
- src/content/pages/knowledgebase/linux/linux-kill-switch-using-the-uncomplicated-firewall-ufw.md
- src/content/pages/knowledgebase/linux/linux-wireguard-kill-switch.md
- src/content/pages/knowledgebase/linux/managing-the-ivpn-linux-client-at-system-boot.md
- src/content/pages/knowledgebase/troubleshooting/how-to-submit-vpn-diagnostic-logs-to-ivpn.md
- src/content/pages/setup/router/opnsense.md
- src/content/pages/setup/router/pfsense.md
> Fix 'kill switch' phrase; minor consistency updates

- src/content/pages/setup/router/pfsense-wireguard.md
> pfSense guide update

- src/content/pages/apps-android.md
> New Android client version 2.3.0

- src/content/pages/setup/router/pfsense-wireguard.md
- src/content/pages/setup/router/pfsense.md
> Update minor details in the pfSense WireGuard guide

- src/themes/ivpn-v3/layouts/partials/footer.html
> Disable RocketChat LiveChat widget for mobile devices

- .github/CONTRIBUTING.md
**Git Workflow** section is updated in `CONTRIBUTING.md` document.
Resolves #117
> Update Contributing Guidelines

- src/content/blog/why-you-dont-need-a-vpn.md
Adding DoINeedAVPN reference and Reddit link to 'Why you don't need a VPN' blog post.
> Blog post content update

- src/content/pages/apps-android.md
> Add reference to split tunnel on Android app page

- src/content/pages/knowledgebase/general/how-many-devices-or-simultaneous-connections-can-i-have-to-ivpn.md
Confirmed this change with IVPN management team.
> Update article for new account area.

- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> App update/3.3.5

- src/content/pages/knowledgebase/general/do-you-support-chromebook.md
ChromeOS is not officially supported and bugs will not be addresses: https://github.com/ivpn/android-app/issues/32
> Update position on ChromeOS support

- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> Desktop app updates/v3.3.7

- src/content/pages/apps-android.md
> Android client v2.4.0

- src/content/pages/apps-android.md
> New Android IVPN client 2.4.1

- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> Desktop app updates/v3.3.10

- src/content/pages/apps-linux.md
- src/themes/ivpn-v3/assets/scss/elements/pre.scss
> Update Debian-like install instructions; apt-key is deprecated

- src/content/pages/knowledgebase/linux/linux-how-do-i-prevent-vpn-leaks-using-iptables.md
- src/themes/ivpn-v3/assets/scss/elements/pre.scss
> Fix code block style issue

- src/themes/ivpn-v3/assets/js/menu.js
> Apps URL not updated in the main menu

- src/content/pages/knowledgebase/macos/macos-launch-at-login-is-not-available.md
> Add macOS KB article for launch at login

- src/content/blog/new-ivpn-linux-app-with-gui-now-available.md
- src/content/pages/apps-ios.md
- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> Update GitHub repo URL

- src/content/pages/privacy-guides/raspberry-pi-2-ivpn-gateway.md
> RaspPi Privacy Guide: Fix link, fix company name, fix comment in iptables rules

- src/themes/ivpn-v3/assets/js/menu.js
> Connection info browser cache issue

- src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
> Handle Braintree "authentication_unavailable" error

- src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
> Fix typo about WireGuard DNS IP address and clarify DNS IP availability.

- src/content/pages/knowledgebase/general/wireguard-faq.md
> Fix missing bold for questions in WireGuard FAQ

- src/content/pages/knowledgebase/linux/managing-the-ivpn-linux-client-at-system-boot.md
> Fixes #189 : update systemd unit file

- src/content/pages/setup/router/openwrt-wireguard.md
> fixing typos

- src/themes/ivpn-v3/package.json
- src/themes/ivpn-v3/yarn.lock
> Upgrade dependencies

- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> App update/desktop/3.3.20

- src/content/pages/apps-android.md
> Android client 2.5.0  version

- src/content/pages/apps-android.md
> Android version 2.5.1

- src/content/pages/apps-android.md
> New Android client version 2.5.2

- src/content/pages/apps-ios.md
- src/content/pages/apps-windows.md
> apps minimum requirements update

- src/content/pages/apps-android.md
> New Android version 2.6.0

- src/themes/ivpn-v3/layouts/_default/baseof.html
> App download drop down not working in iOS Safari

- src/content/pages/ethics.md
Table formatting needs review - my md table implementation does not follow previously implemented format.
> Improve Ethics page (how we don't do marketing)

- src/content/pages/ethics.md
The "Privacy Policy" link on the Ethics page links back to the Ethics page.
This changes the link to properly point to the Privacy page.
> Fix privacy policy link

- src/content/pages/supported-projects.md
> It's Tor not TOR

- src/content/pages/what-is-vpn.md
> Fix a sentence on the What is a VPN page

- src/content/blog/why-you-dont-need-a-vpn.md
Move update to end of Why you don't need a VPN blog post so we can use it as a landing page
> Update Why you don't need a VPN

- src/content/pages/apps-linux.md
> Update apps-linux.md -> removed 'beta' sign

- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> Stenya desktop app release 3.3.30

- src/content/pages/setup/windows-10-wireguard.md
> Add link to official WireGuard client download page

- src/themes/ivpn-v3/assets/js/views/Account/Settings.vue
- src/themes/ivpn-v3/assets/js/views/Account/Settings/Authentication.vue
> Add warning about apps when enabling 2FA in the client area

- src/content/pages/knowledgebase/general/split-tunnel-uses-and-limitations.md
> KB: Add split tunnel limitations article

- src/content/pages/knowledgebase/general/can-i-access-hulu-or-netflix-or-bbc-iplayer-using-ivpn.md
> Split Tunnel for streaming

- src/content/pages/apps-windows.md
> Desktop app release v3.3.40 (Windows)

- src/content/pages/knowledgebase/general/can-i-access-hulu-or-netflix-or-bbc-iplayer-using-ivpn.md
> fixing typo

- src/content/pages/apps-windows.md
Add Split tunneling in the list of features on the Windows app page.
> Add Split tunneling in the list of features

- src/themes/ivpn-v3/assets/scss/components/servers.scss
> Server status page: Expanded server collapses with a click making copying the WG key difficult

- src/content/pages/manifesto.md
- src/themes/ivpn-v3/assets/scss/base.scss
- src/themes/ivpn-v3/assets/scss/components/eof.scss
- src/themes/ivpn-v3/assets/scss/mixins/blink-me.scss
- src/themes/ivpn-v3/assets/scss/pages.scss
Small UI update for Manifesto page.
> Small UI update for Manifesto page

- src/content/pages/home.md
- src/themes/ivpn-v3/assets/scss/components/team.scss
- src/themes/ivpn-v3/layouts/partials/blocks/heading_text_two_cta_two_column.html
- src/themes/ivpn-v3/layouts/partials/blocks/usps_three_column_home.html
Remove theme switcher on the Home page
> Remove theme switcher on the Home page

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
- src/themes/ivpn-v3/assets/scss/components/select.scss
- src/themes/ivpn-v3/assets/scss/components/servers.scss
- src/themes/ivpn-v3/assets/scss/config/grid.scss
> Servers status page update

- src/content/pages/knowledgebase/linux/linux-tray-icon-is-missing-in-gnome.md
> KB: Add GNOME tray article

- src/content/pages/setup/ios-wireguard.md
> minor edits

- src/content/pages/home.md
> Reason to use VPN

- src/content/pages/apps-linux.md
> Linux app: Arch helper details

- src/content/pages/apps-android.md
> New Android client version 2.7.1

- src/content/pages/apps-android.md
> Android client version 2.8.0

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
> Add MultiHop port in Servers status page

- src/content/pages/apps-macos.md
- src/themes/ivpn-v3/assets/scss/components/content.scss
- src/themes/ivpn-v3/layouts/pages/apps.html
> macOS app M1 release

- src/content/pages/pricing-teams.md
- src/themes/ivpn-v3/assets/js/views/Prices.vue
- src/themes/ivpn-v3/assets/scss/components/price-box.scss
- src/themes/ivpn-v3/assets/scss/pages.scss
> New teams pricing page

- src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
> Show specific error message for 3D Secure failure

- src/content/pages/knowledgebase/ios/native-ios-kill-switch-known-issues.md
> Update "Known issues with Native iOS Kill Switch" article

- src/content/pages/privacy-guides/18-questions-to-ask-your-vpn-service-provider.md
One link at `/privacy-guides/18-questions-to-ask-your-vpn-service-provider/` has one malformed link.
- `(official page)[https://www.wireguard.com]`
Fixed the link format so now it should render properly.
None
> Fix malformed link format

- src/content/pages/knowledgebase/general/wireguard-faq.md
- src/content/pages/pptp-vs-ipsec-ikev2-vs-openvpn-vs-wireguard.md
- src/content/pages/wireguard-vpn.md
> Protocol comparison page edits

- src/content/pages/apps-android.md
> Android release 2.8.1

- src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
> Update Braintree 3D Secure error handling

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
> Column sorting on server status page works once, then cannot be sorted again

- src/content/pages/knowledgebase/windows/windows-how-to-establish-rdp-connection-to-a-computer-running-ivpn.md
> Update: fix default RDP port

- src/content/pages/privacy-guides/how-to-perform-a-vpn-leak-test.md
> Update: How to perform a VPN leak test

- src/content/pages/privacy-guides/online-privacy-through-opsec-and-compartmentalization-part-4.md
> Update: Online Privacy Through OPSEC and Compartmentalization: Part 4

- src/content/pages/privacy-guides/online-privacy-through-opsec-and-compartmentalization-part-3.md
> Fixing some 404s

- src/content/pages/antitracker.md
- src/content/pages/knowledgebase/general/antitracker-faq.md
- src/content/pages/knowledgebase/linux/linux-webpages-do-not-load-or-dns-leaks-when-connecting-via-networkmanager.md
- src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
- src/content/pages/setup/android-wireguard.md
- src/content/pages/setup/ios-wireguard.md
- src/content/pages/setup/linux-wireguard-netman.md
- src/content/pages/setup/router/openwrt-wireguard.md
- src/content/pages/setup/router/openwrt.md
- src/content/pages/setup/router/opnsense-wireguard.md
- src/content/pages/setup/router/opnsense.md
- src/content/pages/setup/router/pfsense-wireguard.md
> Update: Hardcore Mode domains

- src/content/pages/setup/router/asuswrt.md
- src/content/pages/setup/router/ddwrt-manual.md
- src/content/pages/setup/router/ddwrt-wireguard.md
- src/content/pages/setup/router/openwrt-wireguard.md
- src/content/pages/setup/router/openwrt.md
- src/content/pages/setup/router/opnsense-wireguard.md
- src/content/pages/setup/router/opnsense.md
- src/content/pages/setup/router/pfsense-wireguard.md
- src/content/pages/setup/router/pfsense.md
- src/content/pages/setup/router/tomato-manual.md
> Update multi-hop reference in the router setup guides

- src/content/pages/privacy-guides/online-privacy-through-opsec-and-compartmentalization-part-2.md
> Update: Online Privacy Through OPSEC and Compartmentalization: Part 2

- src/content/pages/privacy-guides/advanced-privacy-and-anonymity-part-8.md
> Update: Advanced Privacy and Anonymity Using VMs VPNs Tor Part 8

- src/content/blog/misleading-promises-of-the-worlds-fastest-anonymous-military-grade-vpns.md
- src/content/blog/privacy-issue-real-vpns-alone-cant-solve-it.md
- src/content/blog/vpns-are-imperfect-but-necessary-privacy-enhancing-tools.md
- src/content/blog/who-owns-your-vpn-you-should-find-out.md
- src/content/blog/why-you-dont-need-a-vpn.md
- src/content/categories/industry-insights/_index.md
- src/content/categories/vpn-worst-practices/_index.md
> Rename VPN Worst Practices

- src/content/pages/privacy-guides/advanced-privacy-and-anonymity-part-4.md
> Update: Advanced Privacy and Anonymity Using VMs VPNs Tor Part 4

- src/themes/ivpn-v3/data/manifest-example.json
> Add manifest-example.json

- src/content/pages/pricing-teams.md
Added monero below bitcoin
Some new text
N/A
Added new text so people know that monero is supported
> Added Monero to the payment options page

- src/static/ .well-known/apple-app-site-association
> Add apple-app-site-association file

- src/content/blog/wireguard-port-forwarding-enabled.md
- src/themes/ivpn-v3/assets/js/views/Account/PortForwarding.vue
> WireGuard Port Forwarding release

- src/content/pages/apps-android.md
- src/content/pages/apps-ios.md
- src/content/pages/apps-linux-legacy.md
- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
- src/content/pages/home.md
- src/content/pages/pptp-vs-ipsec-ikev2-vs-openvpn-vs-wireguard.md
- src/content/pages/wireguard-vpn.md
> pf reference text updates

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/Cash.vue
Add print button in Cash payment page.
> Add print button in Cash payment page

- src/themes/ivpn-v3/assets/scss/components/heading.scss
- src/themes/ivpn-v3/layouts/partials/header.html
> Update header template

- src/content/pages/apps-windows.md
> IVPN client v3.6.4 for Windows

- src/content/pages/supportua-ru.md
- src/content/pages/supportua.md
- src/themes/ivpn-v3/assets/js/api/api.js
- src/themes/ivpn-v3/assets/js/components/SupportUA.vue
- src/themes/ivpn-v3/assets/js/store/index.js
- src/themes/ivpn-v3/assets/js/store/module_contact.js
- src/themes/ivpn-v3/assets/js/supportua.js
- src/themes/ivpn-v3/assets/scss/elements/input.scss
- src/themes/ivpn-v3/layouts/_default/baseof.html
- src/themes/ivpn-v3/layouts/pages/supportua-ru.html
- src/themes/ivpn-v3/layouts/pages/supportua.html
- src/themes/ivpn-v3/webpack.mix.js
> Support UA page

- src/themes/ivpn-v3/assets/js/styles/vpn-configuration.scss
- src/themes/ivpn-v3/assets/js/views/Account/Wireguard.vue
- src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
> WireGuard configuration in the Account settings

- src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
> Update BraintreeCc.vue template

- src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
> Add key comment in WireGuard configuration

- src/content/pages/apps-android.md
> Android v2.8.2 release

- src/content/blog/ivpn-apps-security-audit-2022-concluded.md
> 2022 audit blog post

- src/themes/ivpn-v3/assets/js/views/Prices.vue
> Update template in Prices.vue

- src/content/pages/apps-linux.md
- src/themes/ivpn-v3/assets/scss/elements/pre.scss
> Update code highlight element

- src/content/pages/apps-linux.md
> Linux setup page update

- src/content/pages/knowledgebase/troubleshooting/how-to-disable-enhanced-app-authentication-eaa.md
> Add KB article: how to disable EAA

- .github/CONTRIBUTING.md
> Start using Conventional Commits specification

- src/content/pages/knowledgebase/general/do-you-support-tunnelblick-or-viscosity.md
[This page](https://www.ivpn.net/knowledgebase/general/do-you-support-tunnelblick-or-viscosity/) says Tunnelbrick instead of Tunnelblick.
It now says Tunnelblick.
N/A
> Fix Tunnelblick typo (Tunnelbrick -> Tunnelblick)

- src/themes/ivpn-v3/layouts/partials/footer.html
> Spelling correction

- src/content/pages/knowledgebase/general/antitracker-faq.md
- src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
> AntiTracker DNS changes for multi-hop

- src/content/pages/knowledgebase/troubleshooting/my-vpn-is-connected-but-i-cannot-browse-the-internet-why.md
> Link to submitting VPN diagnostics logs page sends you to a 404

- src/themes/ivpn-v3/assets/js/components/OpenvpnConfig.vue
> Update verify-x509-name in OpenVPN configurator

- src/content/blog/2019-06-11-block-ads-and-beat-data-surveillance-with-ivpns-antitracker.md
> Update: AntiTracker blog post, domains

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
> Make server load format consistent on /status page

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
> Add Socks5 information on servers status page

- src/content/pages/apps-linux.md
> Update: Include snap info

- src/content/pages/knowledgebase/troubleshooting/my-real-location-is-detected-when-connected-to-vpn-how-to-disable-geolocation.md
N/A
N/A
This change is negligible at best, so not adding myself to the `AUTHORS` file as suggested by the contribution guide.
> docs(typo): replace aas with as

- src/content/pages/knowledgebase/general/do-you-allow-p2p-or-bittorrent-or-torrents-downloading.md
> kb article update

- src/themes/ivpn-v3/assets/scss/elements/body.scss
Make dark scroll bar in dark theme in Chromium-based browsers
> Make dark scroll bar in dark theme in Chromium-based browsers

- src/content/pages/contactus.md
> Remove spaces in mailto: links

- src/content/pages/knowledgebase/troubleshooting/error-connecting-to-ivpn-daemon.md
> Add KB article: daemon error

- src/themes/ivpn-v3/assets/js/components/SelectPaymentMethod.vue
> Move Gift Code to regular payment option buttons

- src/themes/ivpn-v3/assets/js/views/Account/ChangeProduct/ChangeProduct.vue
> Terms clarification text change on Change Product page

- src/themes/ivpn-v3/assets/js/components/SelectPaymentMethod.vue
- src/themes/ivpn-v3/assets/js/router/index.js
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/GiftCard.vue
> "Gift card" to "Voucher"

- src/themes/ivpn-v3/assets/js/views/Prices.vue
Update "Anti-tracker" to "AntiTracker" on pricing page.
> Update AntiTracker label

- src/content/blog/ivpn-infrastructure-fifth-audit-announcement.md
- src/content/pages/home.md
> Audit announcement post

- src/content/pages/knowledgebase/general/configuring-the-ivpn-app-to-autoconnect.md
> New KB article - Configuring the IVPN app to autoconnect

- src/content/pages/apps-linux.md
- src/themes/ivpn-v3/assets/scss/components/highlight.scss
> Update Debian-like repo install commands for extra system hardening

- src/content/pages/knowledgebase/general/how-can-i-connect-to-the-multihop-network.md
> Update Multi-hop article with obfsproxy details

- src/content/pages/setup/router/_index.md
> Add generator links to router page

- src/content/pages/transparency-report.md
It adds the current year to the `transparency-report` table.
Currently it only displays transparency reports all the way up until 2022.
> Add 2023 to transparency-report

- src/content/pages/knowledgebase/ios/native-ios-kill-switch-known-issues.md
> Update KB article: Native iOS Kill Switch

- src/content/pages/knowledgebase/general/custom-dns.md
> custom dns kb article update

- src/content/pages/knowledgebase/linux/linux-how-do-i-prevent-vpn-leaks-using-nftables-and-openvpn.md
Like the **iptables** article, but for **nftables**.
https://www.ivpn.net/knowledgebase/linux/linux-how-do-i-prevent-vpn-leaks-using-iptables/
> Add KB article: Linux - kill switch with nftables, OpenVPN

- src/content/pages/apps-android.md
- src/content/pages/apps-ios.md
- src/content/pages/apps-linux.md
- src/content/pages/apps-macos.md
- src/content/pages/apps-windows.md
> Update Custom DNS in apps features list

- src/content/pages/apps-linux.md
- src/content/pages/knowledgebase/linux/fedora-silverblue.md
> IVPN on Fedora Silverblue setup guide

- src/content/pages/knowledgebase/troubleshooting/how-do-i-verify-the-location-of-server.md
> Update ping test link

- src/content/blog/2023-03-15-ivpn-infrastructure-audit-concluded.md
> Add infrastructure audit blog post

- src/themes/ivpn-v3/assets/js/views/Account/ThankYou.vue
> Update styles in ThankYou.vue

- src/content/pages/apps-android.md
> Update apps-android.md page

- src/themes/ivpn-v3/layouts/partials/header.html
> Add a blue strip promo to specific pages on the website

- src/content/pages/knowledgebase/linux/building-the-ivpn-cli-client-for-linux-on-a-raspberry-pi.md
> Update Raspberry Pi article for May 2023

- src/content/pages/knowledgebase/general/do-you-support-port-forwarding.md
- src/content/pages/knowledgebase/general/how-do-i-remotely-connect-to-my-home-system-or-services-behind-the-vpn-connection.md
> PF kb articles

- src/content/blog/2023-06-29-gradual-removal-of-port-forwarding.md
- src/content/pages/refunds.md
- src/themes/ivpn-v3/assets/js/components/AccountMenu.vue
- src/themes/ivpn-v3/assets/js/views/Account/PortForwarding.vue
- src/themes/ivpn-v3/assets/js/views/Prices.vue
- [ x] Feature
Port Forwarding is not available anymore for new accounts and limited for old accounts.
- [ x] No
> Port forwarding update

- src/content/pages/apps-android.md
> Android v2.9.0 release

- src/content/pages/home.md
> Update home.md: IP -> IP address

- src/themes/ivpn-v3/assets/scss/config/text.scss
- src/themes/ivpn-v3/assets/scss/elements/headings.scss
> Decrease h1 and h2 size in blog templates

- src/content/blog/2015-10-28-port-forwarding-reservations-now-available.md
- src/content/blog/2019-11-29-introducing-a-new-ivpn-subscription-plan.md
- src/content/blog/wireguard-port-forwarding-enabled.md
Added a warning that Port Forwarding is being phased out to earlier blog posts that reference it
> Blog post updates and warnings about PF removal

- src/content/pages/knowledgebase/ios/native-ios-kill-switch-known-issues.md
> ios kill switch kb article update

- src/content/pages/apps-android.md
> Android v2.10.0 release

- src/themes/ivpn-v3/assets/js/views/Prices.vue
> Pricing page update

- AUTHORS
- LICENSE.md
- src/content/blog/2023-08-10-name-change-from-privatus-to-ivpn-limited.md
- src/content/pages/legal-process-guidelines.md
- src/content/pages/team.md
- src/content/pages/terms-of-service.md
- src/content/pages/trust.md
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/Cash.vue
- src/themes/ivpn-v3/assets/js/views/Account/Invoice.vue
> Add company name change blog post

- src/themes/ivpn-v3/assets/js/views/Account/ChangeProduct/ChangeProduct.vue
> Remove port forwarding references on upgrade product area

- src/content/pages/apps-android.md
> Android v2.10.1 release

- src/content/pages/antitracker.md
- src/content/pages/knowledgebase/general/antitracker-faq.md
- src/content/pages/knowledgebase/general/antitracker-plus-lists-explained.md
- src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
> KB update: AntiTracker mentions part 1

- src/content/pages/apps-android.md
> Android v2.10.3 release

- src/content/pages/light.md
- [ x] Code style update
- [x ] No
> change light page metadata

- src/content/pages/apps-android.md
> Android v2.10.4 release

- src/themes/ivpn-v3/assets/js/views/OnePageCheckout.vue
> bug: Fix session not cleaned on light signup

- src/content/pages/knowledgebase/troubleshooting/how-can-i-reset-my-dns-settings.md
The links are not working (404) because the page has been renamed.
The links are working.
N/A
> Fix links to "How do I clear or flush my DNS cache?"

- src/content/blog/launch-ivpn-light-short-term-vpn-paid-btc-lightning.md
- src/content/pages/refunds.md
> refund changes and blog post fix for IVPN Light

- src/themes/ivpn-v3/assets/js/app.js
- src/themes/ivpn-v3/assets/js/components/AccountInfo.vue
- src/themes/ivpn-v3/assets/js/components/AccountMenu.vue
- src/themes/ivpn-v3/assets/js/router/index.js
- src/themes/ivpn-v3/assets/js/store/index.js
- [x ] Feature
- [ x] No
Port forwarding feature deprecation
> Remove port forwarding menu link and route from client area

- src/content/pages/pptp-vs-ipsec-ikev2-vs-openvpn-vs-wireguard.md
Protocol comparison page mentions that WireGuard is a good choice if Multi-hop and port forwarding are not required.  PF is removed and Milti-hop is now supported.
--
Thanks.
> Protocol comparison page: update WireGuard features

- src/content/pages/refunds.md
> Refund text change

- src/content/pages/apps-ios.md
- src/content/pages/apps-linux.md
- src/content/pages/apps-windows.md
> Update app pages subtitle

- src/themes/ivpn-v3/assets/js/components/ServerList.vue
> Add SOCKS5 proxy port number to Server Status page

- src/content/pages/knowledgebase/general/split-tunnel-faq.md
> Add Split Tunnel FAQ

- src/themes/ivpn-v3/assets/js/views/Login.vue
> Make the "Account ID" login form the default one

- src/themes/ivpn-v3/assets/js/views/Login.vue
> Login validation does not ignore spaces before and/or after the account ID/Email

- src/content/pages/knowledgebase/general/antitracker-plus-lists-explained.md
> Edit: update AT+ lists

- src/themes/ivpn-v3/assets/js/api/api.js
- src/themes/ivpn-v3/assets/js/styles/vpn-configuration.scss
- src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
> Improve wireguard config generator

- src/content/pages/knowledgebase/troubleshooting/my-vpn-is-connected-but-i-cannot-browse-the-internet-why.md
> Fix broken URL in my-vpn-is-connected-but-i-cannot-browse-the-internet-why.md

- src/content/pages/apps-android.md
> Android v2.10.5 release

- src/content/pages/transparency-report.md
> Add 2024 entries to our Transparency report

- src/content/pages/transparency-report.md
> Update transparency report

- src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
> Add MultiHop indicator for generated configurations

- src/content/pages/apps-android.md
> Android v2.10.7 release

- src/themes/ivpn-v3/assets/js/api/api.js
- src/themes/ivpn-v3/assets/js/app.js
- src/themes/ivpn-v3/assets/js/components/AccountMenu.vue
- src/themes/ivpn-v3/assets/js/components/Device.vue
- src/themes/ivpn-v3/assets/js/components/PopUp.vue
- src/themes/ivpn-v3/assets/js/components/popups/ChangeProduct.vue
- src/themes/ivpn-v3/assets/js/components/popups/DeleteDevice.vue
- src/themes/ivpn-v3/assets/js/components/popups/DisableDeviceManagement.vue
- src/themes/ivpn-v3/assets/js/components/popups/LogoutDevices.vue
- src/themes/ivpn-v3/assets/js/router/index.js
- src/themes/ivpn-v3/assets/js/store/index.js
- src/themes/ivpn-v3/assets/js/store/module_account.js
- src/themes/ivpn-v3/assets/js/store/module_sessions.js
- src/themes/ivpn-v3/assets/js/views/Account/ChangeProduct/ChangeProduct.vue
- src/themes/ivpn-v3/assets/js/views/Account/DeviceManagement.vue
- src/themes/ivpn-v3/assets/js/views/OnePageCheckout.vue
- [x ] Feature
- [x ] I have read the CONTRIBUTING.md doc
- [x ] I have added necessary documentation (if appropriate)
> Feature: implement device management

- src/content/blog/ivpn-preparing-sixth-security-audit.md
> Next audit blog post announcement

- src/content/pages/knowledgebase/ios/v2ray.md
- src/content/pages/knowledgebase/troubleshooting/i-cannot-connect-from-china-or-vietnam-or-iran-or-russia-etc-what-can-i-do.md
> obfsproxy kb article update

- src/themes/ivpn-v3/assets/js/components/popups/SetPaymentMethod.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/CC.vue
> Bug: Paypal button not working on payment update

- src/content/pages/privacy-guides/mac-address.md
> docs: fix grammar in latest blog post

- src/themes/ivpn-v3/assets/js/views/OnePageCheckout.vue
- [x ] Other... Please describe: Ligthning price update
> task: Update light product prices

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/CC.vue
- src/themes/ivpn-v3/assets/js/views/Prices.vue
- [x ] Bugfix
- [x ] I have read the CONTRIBUTING.md doc
- [x ] I have added necessary documentation (if appropriate)
Issue number: #759
- [x ] No
> bugfix: improve-frontend-error-handling

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/BitCoin.vue
- [ x] Feature
- [x ] I have read the CONTRIBUTING.md doc
- [x ] I have added necessary documentation (if appropriate)
- [x ] No
> Removed bitcoin on-chain payments for weekly payments

- src/themes/ivpn-v3/layouts/partials/footer.html
- [x ] Refactoring (no functional changes, no api changes)
- [x ] No
> task:Remove livechat

- src/themes/ivpn-v3/assets/js/views/OnePageCheckout.vue
- [x ] Feature
- [x ] I have read the CONTRIBUTING.md doc
- [x ] I have added necessary documentation (if appropriate)
- [x ] No
> Replace coingecko url on light page with our API endpoint

- src/content/pages/knowledgebase/linux/linux-webpages-do-not-load-or-dns-leaks-when-connecting-via-networkmanager.md
> style: minor adjustment

- src/themes/ivpn-v3/layouts/partials/head.html
- [x ] Bugfix
Issue number: #778
- [x ] No
> bugfix: Added meta description tag

- src/content/en/pages/apps-android.md
> Android v2.10.8 release

- src/content/en/pages/apps-android.md
- src/content/en/pages/apps-ios.md
- src/themes/ivpn-v3/assets/scss/components/content.scss
- src/themes/ivpn-v3/layouts/pages/apps.html
> Update apps pages

- src/content/es/pages/apps-android.md
- src/content/es/pages/apps-ios.md
> Update ES apps page

- src/content/en/pages/knowledgebase/troubleshooting/how-can-i-access-local-network-devices-like-printers-and-media-servers.md
> KB EN: Add a printer, LAN access article

- src/content/en/pages/pricing-teams.md
> teams policy disclaimer documentation change

- src/config/_default/menus/menus.en.toml
The missing question mark at the end of the question "What is a VPN" is missing and has been bothering me for quite a while.
No question mark
Has question mark.
There might need to be an update to the Spanish version of the footer. I don't speak Spanish so I don't want to overstep.
> Added question mark to the english footer

- src/content/en/pages/apps-android.md
- src/content/es/pages/apps-android.md
> Android v2.10.9 release

- src/themes/ivpn-v3/assets/js/menu.js
- src/themes/ivpn-v3/assets/js/store/module_auth.js
- src/themes/ivpn-v3/layouts/partials/header.html
> Remove free voucher bluestrip

- src/content/en/pages/transparency-report.md
> Transparency report update

- src/content/en/pages/apps-android.md
- src/content/es/pages/apps-android.md
> Android v2.10.10 release

- src/content/en/pages/knowledgebase/general/antitracker-plus-lists-explained.md
Correc wording from `extremly` to `extremely` at antitracker-plus-lists-explained.md . It appear for production at https://www.ivpn.net/knowledgebase/general/antitracker-plus-lists-explained/ .
> [docs] Correct wording from `extremly` to `extremely`.

- nginx.conf
- src/static/.well-known/nostr.json
> Added nostr.json file

- src/themes/ivpn-v3/assets/scss/components/servers.scss
UI issue (select elements) on the Server Status page:
> Server Status UI issue

- src/content/en/pages/knowledgebase/general/antitracker-plus-lists-explained.md
> Remove 1Host Xtra Individual option from AntiTracker documentation

- src/themes/ivpn-v3/locales/en.json
- src/themes/ivpn-v3/locales/es.json
"OBFS4 Public Key" is mislabeled as multi-hop port.
> fix: Server Status page obfs4 key label, EN and ES

- src/content/en/pages/knowledgebase/routers/openwrt-obfs3-and-obfs4-obfuscation-with-obfsproxy-and-openvpn.md
- src/content/en/pages/setup/router/openwrt.md
> docs: Add KB article: OpenWrt + obfs4proxy + OpenVPN

- src/content/en/pages/apps-linux.md
- src/content/es/pages/apps-linux.md
- [y] I have read the CONTRIBUTING.md doc
- [y] The Git workflow follows our guidelines: CONTRIBUTING.md#git
> docs: Update Linux-Fedora repo install commands

- src/content/en/pages/knowledgebase/linux/linux-webpages-do-not-load-or-dns-leaks-when-connecting-via-networkmanager.md
> docs: Reference DNS list for NetworkManager troubleshooting page

- src/content/en/blog/ivpn-year-in-review-2025.md
> blog post yearly review plans

- src/content/en/pages/apps-android.md
- src/content/es/pages/apps-android.md
> Android v2.10.11 release

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/BitCoin.vue
- [ x] Other... Please describe:
> task: Disable temporary lightning payments

- src/content/en/pages/apps-android.md
- src/content/es/pages/apps-android.md
> Android v2.10.12 release

- src/content/en/pages/pptp-vs-ipsec-ikev2-vs-openvpn-vs-wireguard.md
> Fix typo: remove extra 'the'

- src/content/en/pages/transparency-report.md
> transparency report - 2024 finalized, 2025 added (up to 28 February)

- src/content/en/pages/apps-windows.md
- src/content/es/pages/apps-windows.md
- src/themes/ivpn-v3/assets/scss/components/servers.scss
> Add notice to Windows app page about unsupported ARM CPUs

- src/themes/ivpn-v3/assets/js/components/SelectLocationsMulti.vue
> Fix UI for custom drop down (select plan duration)

- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/CC.vue
- src/themes/ivpn-v3/assets/js/views/Account/AddFunds/PayPal.vue
> feature: Improve payment area security for new accounts

- src/content/en/pages/transparency-report.md
- src/content/es/pages/transparency-report.md
> Transparency update
